[package]
name = "git_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.18"
tui = { version = "0.19", features = ["crossterm"], default-features = false }
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
tui-input = "0.8" 